openapi: 3.0.0
info:
  contact:
    email: dev-platform@stripe.com
  description:
    The Stripe REST API. Please see https://stripe.com/docs/api for more
    details.
  title: Stripe API
  version: "2019-11-05"
servers:
  - url: https://api.stripe.com/
paths:
  /v1/account:
    get:
      description: "<p>Retrieves the details of an account.</p>"
      operationId: GetAccount
      responses:
        "200":
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/account"
          description: Successful response.
        default:
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/error"
          description: Error response.
components:
  schemas:
    account:
      properties:
        country:
          description: The account's country.
          maxLength: 5000
          type: string
        created:
          description:
            Time at which the object was created. Measured in seconds since
            the Unix epoch.
          format: unix-time
          type: integer
        email:
          description: The primary user's email address.
          maxLength: 5000
          nullable: true
          type: string
      required:
        - id
        - object
      title: Account
      type: object
    error:
      description: An error response from the Stripe API
      properties:
        error:
          "$ref": "#/components/schemas/api_errors"
      required:
        - error
      type: object
    api_errors:
      properties:
        type:
          description:
            The type of error returned. One of `api_connection_error`,
            `api_error`, `authentication_error`, `card_error`, `idempotency_error`,
            `invalid_request_error`, or `rate_limit_error`
          enum:
            - api_connection_error
            - api_error
            - authentication_error
            - card_error
            - idempotency_error
            - invalid_request_error
            - rate_limit_error
          type: string
      required:
        - type
      title: APIErrors
      type: object
