name: learn-you-a-haskell
version: 0.1.0.0
github: "ksaaskil/functional-programming-examples"
license: BSD3
author: "ksaaskil"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hello-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - filepath
  - containers
  - acme-missiles # added
  - random

library:
  source-dirs: src

executables:
  main-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - learn-you-a-haskell

  todo:
    main: Main.hs
    source-dirs: todo-app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - learn-you-a-haskell
      - directory

tests:
  hello-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hello-haskell
